In [1]:
import numpy as np
import pandas as pd

In [2]:
data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [24, 27, 22],
    "Country": ["USA", "UK", "Canada"]
}

df = pd.DataFrame(data)
print(df)

      Name  Age Country
0    Alice   24     USA
1      Bob   27      UK
2  Charlie   22  Canada

In [3]:
dataList = [
    ["Alice", 24, "USA"],
    ["Bob", 27, "UK"],
    ["Charlie", 22, "Canada"]
]

df = pd.DataFrame(dataList, columns=["Name", "Age", "Country"])

In [4]:
df.head()      # first 5 rows
df.tail()      # last 5 rows
df.shape       # rows and columns
df.columns     # column names
df.index       # index values
df.info()      # data information
df.describe()  # statistics

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     3 non-null      str
 1   Age      3 non-null      int64
 2   Country  3 non-null      str
dtypes: int64(1), str(2)
memory usage: 204.0 bytes

             Age
count   3.000000
mean   24.333333
std     2.516611
min    22.000000
25%    23.000000
50%    24.000000
75%    25.500000
max    27.000000

In [5]:
df["Name"]

0      Alice
1        Bob
2    Charlie
Name: Name, dtype: str

In [6]:
df[["Name", "Age"]]

      Name  Age
0    Alice   24
1      Bob   27
2  Charlie   22

In [7]:
df.loc[0]

Name       Alice
Age           24
Country      USA
Name: 0, dtype: object

In [8]:
df.iloc[1]

Name       Bob
Age         27
Country     UK
Name: 1, dtype: object

In [9]:
df[df["Age"] > 23]

df[df["Country"] == "USA"]

df[(df["Age"] > 23) & (df["Country"] == "USA")]

df[(df["Age"] > 23) | (df["Country"] == "UK")]

    Name  Age Country
0  Alice   24     USA
1    Bob   27      UK

In [10]:
df["Designation"] = ["Developer", "Manager", "Analyst"]

In [11]:
df

      Name  Age Country Designation
0    Alice   24     USA   Developer
1      Bob   27      UK     Manager
2  Charlie   22  Canada     Analyst

In [12]:
df["AgeAfter5Years"] = df["Age"] + 5

In [13]:
df

      Name  Age Country Designation  AgeAfter5Years
0    Alice   24     USA   Developer              29
1      Bob   27      UK     Manager              32
2  Charlie   22  Canada     Analyst              27

In [14]:
df.loc[0, "Age"] = 25

In [15]:
df

      Name  Age Country Designation  AgeAfter5Years
0    Alice   25     USA   Developer              29
1      Bob   27      UK     Manager              32
2  Charlie   22  Canada     Analyst              27

In [16]:
df.drop("Country", axis=1, inplace=True)
print(df)

      Name  Age Designation  AgeAfter5Years
0    Alice   25   Developer              29
1      Bob   27     Manager              32
2  Charlie   22     Analyst              27

In [17]:
df.drop(1, axis=0)
print(df)

      Name  Age Designation  AgeAfter5Years
0    Alice   25   Developer              29
1      Bob   27     Manager              32
2  Charlie   22     Analyst              27

In [19]:
df.rename(columns={"Name": "EmployeeName"}, inplace=True)
print(df)

  EmployeeName  Age Designation  AgeAfter5Years
0        Alice   25   Developer              29
1          Bob   27     Manager              32
2      Charlie   22     Analyst              27

In [20]:
df.sort_values("Age")

df.sort_values("Age", ascending=False)

  EmployeeName  Age Designation  AgeAfter5Years
1          Bob   27     Manager              32
0        Alice   25   Developer              29
2      Charlie   22     Analyst              27

In [22]:
df.set_index("Age")

    EmployeeName Designation  AgeAfter5Years
Age
25         Alice   Developer              29
27           Bob     Manager              32
22       Charlie     Analyst              27

In [23]:
df.reset_index()

   index EmployeeName  Age Designation  AgeAfter5Years
0      0        Alice   25   Developer              29
1      1          Bob   27     Manager              32
2      2      Charlie   22     Analyst              27