In [1]:
import numpy as np
import pandas as pd

### Merging 2 dataframes

In [6]:
employees = pd.DataFrame({
    "EmployeeID": [1, 2, 3],
    "EmployeeName": ["Alice", "Bob", "Charlie"],
    "Department": ["IT", "HR", "Finance"]
})
# DataFrame 2: Salary information
salaries = pd.DataFrame({
    "EmployeeID": [1, 2, 3],
    "Salary": [50000, 60000, 70000],
    "Bonus": [5000, 7000, 8000]
})

In [7]:
employees

   EmployeeID EmployeeName Department
0           1        Alice         IT
1           2          Bob         HR
2           3      Charlie    Finance

In [8]:
salaries

   EmployeeID  Salary  Bonus
0           1   50000   5000
1           2   60000   7000
2           3   70000   8000

In [10]:
pd.merge(employees,salaries)

   EmployeeID EmployeeName Department  Salary  Bonus
0           1        Alice         IT   50000   5000
1           2          Bob         HR   60000   7000
2           3      Charlie    Finance   70000   8000

### Concatination of 2 DataFrames

In [11]:
df1 = pd.DataFrame({
    "EmployeeID": [1, 2],
    "Name": ["Alice", "Bob"],
    "Department": ["IT", "HR"]
})

df2 = pd.DataFrame({
    "EmployeeID": [3, 4],
    "Name": ["Charlie", "David"],
    "Department": ["Finance", "Marketing"]
})

print(df1)
print(df2)

   EmployeeID   Name Department
0           1  Alice         IT
1           2    Bob         HR
   EmployeeID     Name Department
0           3  Charlie    Finance
1           4    David  Marketing

In [12]:
pd.concat([df1,df2])

   EmployeeID     Name Department
0           1    Alice         IT
1           2      Bob         HR
0           3  Charlie    Finance
1           4    David  Marketing

In [13]:
pd.concat([df1,df2], axis = 1)

   EmployeeID   Name Department  EmployeeID     Name Department
0           1  Alice         IT           3  Charlie    Finance
1           2    Bob         HR           4    David  Marketing

### Joining 2 Data-Frames

In [18]:
df1 = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie"],
     
}, index=[1, 2, 3])

df2 = pd.DataFrame({
     
    "Score": [88, 92, 80]
}, index=[2, 3, 4])

In [19]:
df1

      Name
1    Alice
2      Bob
3  Charlie

In [20]:
df2

   Score
2     88
3     92
4     80

In [21]:
df1.join(df2)

      Name  Score
1    Alice    NaN
2      Bob   88.0
3  Charlie   92.0

In [23]:
df2.join(df1)

   Score     Name
2     88      Bob
3     92  Charlie
4     80      NaN