In [1]:
import numpy as np
import pandas as pd

Dataframes Basic Operations

In [2]:
data = {
    "EmpID":      [101, 102, 103, 104, 105, 106, 107, 108],
    "Name":       ["Alice", "Bob", "Carol", "Dave", "Eve", "Frank", "Grace", "Hank"],
    "Department": ["HR", "IT", "Finance", "IT", "HR", "Finance", "IT", "HR"],
    "Age":        [28, 35, 30, 25, 40, 33, 27, 45],
    "Salary":     [50000, 80000, 60000, 72000, 55000, 67000, 76000, 52000],
    "Experience": [3, 10, 6, 2, 15, 8, 4, 20],
    "Rating":     [4.2, 3.8, 4.5, 3.6, 4.8, 4.0, 3.9, 4.1],
    "Active":     [True, True, False, True, True, False, True, True],
}

df1 = pd.DataFrame(data)
df1

   EmpID   Name Department  Age  Salary  Experience  Rating  Active
0    101  Alice         HR   28   50000           3     4.2    True
1    102    Bob         IT   35   80000          10     3.8    True
2    103  Carol    Finance   30   60000           6     4.5   False
3    104   Dave         IT   25   72000           2     3.6    True
4    105    Eve         HR   40   55000          15     4.8    True
5    106  Frank    Finance   33   67000           8     4.0   False
6    107  Grace         IT   27   76000           4     3.9    True
7    108   Hank         HR   45   52000          20     4.1    True

In [3]:
df1.shape

(8, 8)

In [4]:
df1.columns

Index(['EmpID', 'Name', 'Department', 'Age', 'Salary', 'Experience', 'Rating',
       'Active'],
      dtype='str')

In [5]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   EmpID       8 non-null      int64
 1   Name        8 non-null      str
 2   Department  8 non-null      str
 3   Age         8 non-null      int64
 4   Salary      8 non-null      int64
 5   Experience  8 non-null      int64
 6   Rating      8 non-null      float64
 7   Active      8 non-null      bool
dtypes: bool(1), float64(1), int64(4), str(2)
memory usage: 588.0 bytes

In [6]:
df1.describe()

           EmpID        Age        Salary  Experience    Rating
count    8.00000   8.000000      8.000000    8.000000  8.000000
mean   104.50000  32.875000  64000.000000    8.500000  4.112500
std      2.44949   6.875162  11401.754251    6.279217  0.387068
min    101.00000  25.000000  50000.000000    2.000000  3.600000
25%    102.75000  27.750000  54250.000000    3.750000  3.875000
50%    104.50000  31.500000  63500.000000    7.000000  4.050000
75%    106.25000  36.250000  73000.000000   11.250000  4.275000
max    108.00000  45.000000  80000.000000   20.000000  4.800000

In [7]:
df1['Age'] + 5

0    33
1    40
2    35
3    30
4    45
5    38
6    32
7    50
Name: Age, dtype: int64

## DataFrames Applying Funtions

In [8]:
df1

   EmpID   Name Department  Age  Salary  Experience  Rating  Active
0    101  Alice         HR   28   50000           3     4.2    True
1    102    Bob         IT   35   80000          10     3.8    True
2    103  Carol    Finance   30   60000           6     4.5   False
3    104   Dave         IT   25   72000           2     3.6    True
4    105    Eve         HR   40   55000          15     4.8    True
5    106  Frank    Finance   33   67000           8     4.0   False
6    107  Grace         IT   27   76000           4     3.9    True
7    108   Hank         HR   45   52000          20     4.1    True

In [9]:
def square(x):
    return x**2

In [12]:
df1['Experience'] = df1['Experience'].apply(square)

In [13]:
df1

   EmpID   Name Department  Age  Salary  Experience  Rating  Active
0    101  Alice         HR   28   50000           9     4.2    True
1    102    Bob         IT   35   80000         100     3.8    True
2    103  Carol    Finance   30   60000          36     4.5   False
3    104   Dave         IT   25   72000           4     3.6    True
4    105    Eve         HR   40   55000         225     4.8    True
5    106  Frank    Finance   33   67000          64     4.0   False
6    107  Grace         IT   27   76000          16     3.9    True
7    108   Hank         HR   45   52000         400     4.1    True